global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sentinel-vision'
    static_configs:
      - targets: ['localhost:8080'] # Model Serving metrics

  - job_name: 'spark-metrics'
    static_configs:
      - targets: ['spark-master:8081']

  - job_name: 'kafka-metrics'
    static_configs:
      - targets: ['kafka:29092']
