global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sentinel-vision'
    static_configs:
      - targets: ['inference-engine:8080'] # Model Serving metrics

  - job_name: 'vision-module'
    static_configs:
      - targets: ['vision-module:8001']

  - job_name: 'video-generator'
    static_configs:
      - targets: ['video-generator:8000']

  - job_name: 'spark-metrics'
    static_configs:
      - targets: ['spark-master:8081']

  - job_name: 'kafka-metrics'
    static_configs:
      - targets: ['kafka:29092']
